# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    hash_and_equals: error
  exclude:
    - lib/l10n/*.dart

linter:
  rules:
    - hash_and_equals